name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cos40005-web-api:latest

      # - name: Set up SSH Agent
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH }}

      # - name: Pull and run latest Docker image on server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no zlla@zlladaxua.ddns.net "
      #     cd /Users/zlla/Code/COS40005/Server &&
      #     /usr/local/bin/docker-compose down &&
      #     /usr/local/bin/docker-compose pull &&
      #     /usr/local/bin/docker-compose up --build -d
      #     "
